config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
  resources :users, only: [:new, :create]
  resources :appointments
  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin do
    resources :appointments, only: [:index] do
      member do
        post :confirm
        post :cancel
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord

  belongs_to :user
  belongs_to :dentist

  def send_confirmation_sms
    client = Twilio::REST::Client.new(ENV['TWILIO_ID'], ENV['TWILIO_TOKEN'])

    client.api.account.messages.create(
    from: ENV['PHONE_NUMBER'],
    to: "+1#{self.user.phone}",
    body: "You have an Appointment on #{self.appointment_at} with #{self.dentist.name}"
    )
  end
end

app/models/dentist.rb
class Dentist < ApplicationRecord

  has_many :appointments
  has_many :users, through: :appointments

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :appointments
  # has_many :dentists, through: :appointments

  validates :name, :email, :phone, presence: true
  validates :email, uniqueness: true
end

app/controllers/admin/appointments_controller.rb
class Admin::AppointmentsController < Admin::BaseController
  before_action :load_appointment, only: [:confirm, :cancel]

  def index
    @appointments = Appointment.order(created_at: :desc) # we dont care about displaying as the admin is supposed to see all appointments
  end

  def confirm
    @appointment.status = 'confirmed'
    @appointment.save!
    @appointment.send_confirmation_sms
    flash[:notice] = "Appointment has been confirmed"
    redirect_to admin_appointments_url
  end

  def cancel
    @appointment.status = 'canceled'
    @appointment.save!
    flash[:notice] = "Appointment has been thrown in the garbage!"
    redirect_to admin_appointments_url
  end

  private

  def load_appointment
    @appointment = Appointment.find(params[:id])
  end
end

# Admin::AppointmentsController   the Admin:: is the module where AppointmentsController is a class of the module

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  # this is good to have a common controller for all the Admin modules that can be applied to all aspects of admin

  before_action :require_logged_in
  before_action :require_admin_user

  # check the user that is logged in is a current admin?
  def require_admin_user
    unless current_user.is_admin?
      flash[:alert] = "Sorry, Admins only Biatch! :P"
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    User.find(session[:user_id]) if logged_in?
  end

  helper_method :current_user # helper_method lets you use this shorthand in the views as well

  def logged_in?
    session[:user_id].present?
  end

  helper_method :logged_in?

  def require_logged_in
    unless logged_in? # you can put unless logged_in
      flash[:alert] = "Nice try buddy, Log in first you tard!"
      redirect_to new_session_url
    end
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :require_logged_in # what this does? before it runs the code, it will calll method require_logged_in an

  def index
    @appointments = current_user.appointments.order(created_at: :desc)

    # the above is the same as Appointment.where(user_id: current_user.id).all -- we can write the above using the has_many association, we are calling current_user helper method

  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.user_id = current_user.id

    if @appointment.save
      flash[:notice] = "Your appointment has been saved"
      redirect_to appointments_url
    else
      render :new
    end
  end

  private
  # this mehtod passes in the params from the form to the create method
  def appointment_params
    params.require(:appointment).permit(:dentist_id, :appointment_at)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def destroy
    # session[:user_id] = nil  to log the user out, which clears the cookie
    session.clear
    redirect_to root_url
  end

  def new
    # this stays empty becuase we are only showing the login form
  end

  def create
    user = User.find_by(email: params[:session][:email])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to appointments_url
    else
      flash[:alert] = "Email or Password Incorrect"
      render :new
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Hold on to your wallet, you 'bout to get shcammzed"
      session[:user_id] = @user.id # this will remember and keep the user logged in by saving the info in their session cookie
      redirect_to appointments_url
    else
      flash[:alert] = "You dun goofed son! Fix dat chit"
      render :new
    end

  end

  private
  # this mehtod passes in the params from the form to the create method
  def user_params
    params.require(:user).permit(:name, :email, :password, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/appointments/index.html.erb
<h1>Admin Appointment</h1>

<ul>
<% @appointments.each do |appointment| %>
<li>
  <%= appointment.appointment_at %> with <%= appointment.dentist.name %>
  <br>
  <small><%= appointment.status %></small>
  <br>
  <%= link_to 'Confirm', confirm_admin_appointment_path(appointment), method: :post, class: 'btn btn-primary' %> |
    <%= link_to 'Cancel', cancel_admin_appointment_path(appointment), method: :post, class: 'btn btn-danger' %>

</li>
<% end %>

</ul>

app/views/appointments/index.html.erb
<h2>Appointments</h2>

<%= link_to 'New Appointment', new_appointment_path %>

<ul>

<% @appointments.each do |appointment| %>
<li>
  <%= appointment.appointment_at %> with <%= appointment.dentist.name %>
  <br>
  <small><%= appointment.status %></small>
</li>
<% end %>
</ul>

app/views/appointments/new.html.erb
<h2>New Appointment</h2>

<%= form_for @appointment do |f| %>

<div class="form-group">
  <%= f.label :denist_id %>
  <%= f.collection_select :dentist_id, Dentist.order(:name), :id, :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :appointment_at %>
  <%= f.datetime_field :appointment_at, class: 'form-control' %>
</div>



<div class="form-group">
  <%= f.submit 'Save' %>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrookedDees</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <nav>
      <ul>
        <li>
          <%= link_to 'Home', root_path %>
        </li>

        <% if logged_in? %>
          <li>
            <%= link_to 'My Appointment', appointments_path %>
          </li>
          <!-- we only want to show this link if the user is logged in -->
            <% if current_user.is_admin? %>
              <li>
                <%= link_to 'Admin', admin_appointments_path %>
              </li>
            <% end %>
          <li>
            <%= link_to 'Log Out', session_path(current_user), method: :delete  %>
          </li>
      <% else %>
      <!-- else we want to show the sign up and login  -->
          <li>
            <%= link_to 'Sign Up', new_user_path %>
          </li>
          <li>
            <%= link_to 'Log In', new_session_path %>
          </li>
        <% end %>
      </ul>
    </nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Crooked Dee's Dentistry</h1>

app/views/users/new.html.erb
<h1>New User</h1>
<%= form_for @user do |f| %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>


<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
</div>


<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>
</div>


<div class="form-group">
  <%= f.label :phone %>
  <%= f.phone_field :phone, class: 'form-control' %>
</div>


<div class="form-group">
  <%= f.submit 'Save' %>
</div>

<% end %>